#  https://pre-commit.com/

repos:
  - repo: https://github.com/Payadel/pre-commit-hooks
    rev: v0.1.3
    hooks:
      - id: run-scripts
        name: Run All Before Push
        args: ['-f', 'script/run-all-before-push']
        stages: [push]
      - id: run-scripts
        name: Before Commit
        args: ['-f', 'script/before-commit']
        stages: [commit-msg]
